--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[sp_InsertEFMigrationsHistory]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertEFMigrationsHistory]

IF OBJECT_ID(N'[dbo].[sp_UpdateEFMigrationsHistory]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_UpdateEFMigrationsHistory]

IF OBJECT_ID(N'[dbo].[sp_InsertUpdateEFMigrationsHistory]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertUpdateEFMigrationsHistory]

IF OBJECT_ID(N'[dbo].[sp_DeleteEFMigrationsHistory]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteEFMigrationsHistory]

IF OBJECT_ID(N'[dbo].[sp_DeleteEFMigrationsHistoriesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteEFMigrationsHistoriesDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectEFMigrationsHistory]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectEFMigrationsHistory]

IF OBJECT_ID(N'[dbo].[sp_SelectEFMigrationsHistoriesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectEFMigrationsHistoriesDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectEFMigrationsHistoriesPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectEFMigrationsHistoriesPaged]

IF OBJECT_ID(N'[dbo].[sp_SelectEFMigrationsHistoriesAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectEFMigrationsHistoriesAll]

--endregion

GO

--region [dbo].[sp_InsertEFMigrationsHistory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertEFMigrationsHistory]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertEFMigrationsHistory]
	@MigrationId nvarchar(150),
	@ProductVersion nvarchar(32)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[__EFMigrationsHistory] (
	[MigrationId],
	[ProductVersion]
) VALUES (
	@MigrationId,
	@ProductVersion
)

--endregion

GO

--region [dbo].[sp_UpdateEFMigrationsHistory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_UpdateEFMigrationsHistory]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_UpdateEFMigrationsHistory]
	@MigrationId nvarchar(150),
	@ProductVersion nvarchar(32)
AS

SET NOCOUNT ON

UPDATE [dbo].[__EFMigrationsHistory] SET
	[ProductVersion] = @ProductVersion
WHERE
	[MigrationId] = @MigrationId

--endregion

GO

--region [dbo].[sp_InsertUpdateEFMigrationsHistory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertUpdateEFMigrationsHistory]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertUpdateEFMigrationsHistory]
	@MigrationId nvarchar(150),
	@ProductVersion nvarchar(32)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [MigrationId] FROM [dbo].[__EFMigrationsHistory] WHERE [MigrationId] = @MigrationId)
BEGIN
	UPDATE [dbo].[__EFMigrationsHistory] SET
		[ProductVersion] = @ProductVersion
	WHERE
		[MigrationId] = @MigrationId
END
ELSE
BEGIN
	INSERT INTO [dbo].[__EFMigrationsHistory] (
		[MigrationId],
		[ProductVersion]
	) VALUES (
		@MigrationId,
		@ProductVersion
	)
END

--endregion

GO

--region [dbo].[sp_DeleteEFMigrationsHistory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteEFMigrationsHistory]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteEFMigrationsHistory]
	@MigrationId nvarchar(150)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[__EFMigrationsHistory]
WHERE
	[MigrationId] = @MigrationId

--endregion

GO

--region [dbo].[sp_DeleteEFMigrationsHistoriesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteEFMigrationsHistoriesDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteEFMigrationsHistoriesDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[__EFMigrationsHistory]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectEFMigrationsHistory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectEFMigrationsHistory]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectEFMigrationsHistory]
	@MigrationId nvarchar(150)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[MigrationId],
	[ProductVersion]
FROM
	[dbo].[__EFMigrationsHistory]
WHERE
	[MigrationId] = @MigrationId

--endregion

GO

--region [dbo].[sp_SelectEFMigrationsHistoriesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectEFMigrationsHistoriesDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectEFMigrationsHistoriesDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[MigrationId],
	[ProductVersion]
FROM
	[dbo].[__EFMigrationsHistory]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectEFMigrationsHistoriesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectEFMigrationsHistoriesAll]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectEFMigrationsHistoriesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[MigrationId],
	[ProductVersion]
FROM
	[dbo].[__EFMigrationsHistory]

--endregion

GO

--region [dbo].[sp_SelectEFMigrationsHistoriesPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectEFMigrationsHistoriesPaged]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectEFMigrationsHistoriesPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[MigrationId],
	[ProductVersion]
FROM
	[dbo].[__EFMigrationsHistory]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[sp_InsertCountry]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertCountry]

IF OBJECT_ID(N'[dbo].[sp_UpdateCountry]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_UpdateCountry]

IF OBJECT_ID(N'[dbo].[sp_InsertUpdateCountry]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertUpdateCountry]

IF OBJECT_ID(N'[dbo].[sp_DeleteCountry]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteCountry]

IF OBJECT_ID(N'[dbo].[sp_DeleteCountriesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteCountriesDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectCountry]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectCountry]

IF OBJECT_ID(N'[dbo].[sp_SelectCountriesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectCountriesDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectCountriesPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectCountriesPaged]

IF OBJECT_ID(N'[dbo].[sp_SelectCountriesAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectCountriesAll]

--endregion

GO

--region [dbo].[sp_InsertCountry]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertCountry]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertCountry]
	@Name nvarchar(100),
	@Id int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Country] (
	[Name]
) VALUES (
	@Name
)

SET @Id = SCOPE_IDENTITY()

--endregion

GO

--region [dbo].[sp_UpdateCountry]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_UpdateCountry]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_UpdateCountry]
	@Id int,
	@Name nvarchar(100)
AS

SET NOCOUNT ON

UPDATE [dbo].[Country] SET
	[Name] = @Name
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_InsertUpdateCountry]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertUpdateCountry]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertUpdateCountry]
	@Id int,
	@Name nvarchar(100)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [Id] FROM [dbo].[Country] WHERE [Id] = @Id)
BEGIN
	UPDATE [dbo].[Country] SET
		[Name] = @Name
	WHERE
		[Id] = @Id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Country] (
		[Id],
		[Name]
	) VALUES (
		@Id,
		@Name
	)
END

--endregion

GO

--region [dbo].[sp_DeleteCountry]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteCountry]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteCountry]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Country]
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_DeleteCountriesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteCountriesDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteCountriesDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Country]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectCountry]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectCountry]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectCountry]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Name]
FROM
	[dbo].[Country]
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_SelectCountriesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectCountriesDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectCountriesDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[Id],
	[Name]
FROM
	[dbo].[Country]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectCountriesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectCountriesAll]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectCountriesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Name]
FROM
	[dbo].[Country]

--endregion

GO

--region [dbo].[sp_SelectCountriesPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectCountriesPaged]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectCountriesPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Name]
FROM
	[dbo].[Country]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[sp_InsertService]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertService]

IF OBJECT_ID(N'[dbo].[sp_UpdateService]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_UpdateService]

IF OBJECT_ID(N'[dbo].[sp_InsertUpdateService]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertUpdateService]

IF OBJECT_ID(N'[dbo].[sp_DeleteService]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteService]

IF OBJECT_ID(N'[dbo].[sp_DeleteServicesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteServicesDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectService]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectService]

IF OBJECT_ID(N'[dbo].[sp_SelectServicesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectServicesDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectServicesPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectServicesPaged]

IF OBJECT_ID(N'[dbo].[sp_SelectServicesAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectServicesAll]

IF OBJECT_ID(N'[dbo].[sp_SelectServicesByCountryId]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectServicesByCountryId]

IF OBJECT_ID(N'[dbo].[sp_DeleteServicesByCountryId]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteServicesByCountryId]

--endregion

GO

--region [dbo].[sp_InsertService]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertService]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertService]
	@Name nvarchar(100),
	@PriceHour decimal(18, 2),
	@CountryId int,
	@Id int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Services] (
	[Name],
	[PriceHour],
	[CountryId]
) VALUES (
	@Name,
	@PriceHour,
	@CountryId
)

SET @Id = SCOPE_IDENTITY()

--endregion

GO

--region [dbo].[sp_UpdateService]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_UpdateService]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_UpdateService]
	@Id int,
	@Name nvarchar(100),
	@PriceHour decimal(18, 2),
	@CountryId int
AS

SET NOCOUNT ON

UPDATE [dbo].[Services] SET
	[Name] = @Name,
	[PriceHour] = @PriceHour,
	[CountryId] = @CountryId
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_InsertUpdateService]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertUpdateService]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertUpdateService]
	@Id int,
	@Name nvarchar(100),
	@PriceHour decimal(18, 2),
	@CountryId int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [Id] FROM [dbo].[Services] WHERE [Id] = @Id)
BEGIN
	UPDATE [dbo].[Services] SET
		[Name] = @Name,
		[PriceHour] = @PriceHour,
		[CountryId] = @CountryId
	WHERE
		[Id] = @Id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Services] (
		[Id],
		[Name],
		[PriceHour],
		[CountryId]
	) VALUES (
		@Id,
		@Name,
		@PriceHour,
		@CountryId
	)
END

--endregion

GO

--region [dbo].[sp_DeleteService]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteService]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteService]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Services]
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_DeleteServicesByCountryId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteServicesByCountryId]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteServicesByCountryId]
	@CountryId int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Services]
WHERE
	[CountryId] = @CountryId

GO

--endregion

GO

--region [dbo].[sp_DeleteServicesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteServicesDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteServicesDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Services]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectService]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectService]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectService]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Name],
	[PriceHour],
	[CountryId]
FROM
	[dbo].[Services]
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_SelectServicesByCountryId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectServicesByCountryId]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectServicesByCountryId]
	@CountryId int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Name],
	[PriceHour],
	[CountryId]
FROM
	[dbo].[Services]
WHERE
	[CountryId] = @CountryId

--endregion

GO

--region [dbo].[sp_SelectServicesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectServicesDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectServicesDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[Id],
	[Name],
	[PriceHour],
	[CountryId]
FROM
	[dbo].[Services]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectServicesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectServicesAll]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectServicesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Name],
	[PriceHour],
	[CountryId]
FROM
	[dbo].[Services]

--endregion

GO

--region [dbo].[sp_SelectServicesPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectServicesPaged]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectServicesPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[Name],
	[PriceHour],
	[CountryId]
FROM
	[dbo].[Services]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[sp_InsertSupplier]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertSupplier]

IF OBJECT_ID(N'[dbo].[sp_UpdateSupplier]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_UpdateSupplier]

IF OBJECT_ID(N'[dbo].[sp_InsertUpdateSupplier]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_InsertUpdateSupplier]

IF OBJECT_ID(N'[dbo].[sp_DeleteSupplier]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteSupplier]

IF OBJECT_ID(N'[dbo].[sp_DeleteSuppliersDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteSuppliersDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectSupplier]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectSupplier]

IF OBJECT_ID(N'[dbo].[sp_SelectSuppliersDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectSuppliersDynamic]

IF OBJECT_ID(N'[dbo].[sp_SelectSuppliersPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectSuppliersPaged]

IF OBJECT_ID(N'[dbo].[sp_SelectSuppliersAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectSuppliersAll]

IF OBJECT_ID(N'[dbo].[sp_SelectSuppliersByServicesId]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_SelectSuppliersByServicesId]

IF OBJECT_ID(N'[dbo].[sp_DeleteSuppliersByServicesId]') IS NOT NULL
	DROP PROCEDURE [dbo].[sp_DeleteSuppliersByServicesId]

--endregion

GO

--region [dbo].[sp_InsertSupplier]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertSupplier]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertSupplier]
	@NIT int,
	@Name nvarchar(100),
	@Email nvarchar(100),
	@ServicesId int,
	@Id int OUTPUT
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Supplier] (
	[NIT],
	[Name],
	[Email],
	[ServicesId]
) VALUES (
	@NIT,
	@Name,
	@Email,
	@ServicesId
)

SET @Id = SCOPE_IDENTITY()

--endregion

GO

--region [dbo].[sp_UpdateSupplier]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_UpdateSupplier]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_UpdateSupplier]
	@Id int,
	@NIT int,
	@Name nvarchar(100),
	@Email nvarchar(100),
	@ServicesId int
AS

SET NOCOUNT ON

UPDATE [dbo].[Supplier] SET
	[NIT] = @NIT,
	[Name] = @Name,
	[Email] = @Email,
	[ServicesId] = @ServicesId
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_InsertUpdateSupplier]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_InsertUpdateSupplier]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_InsertUpdateSupplier]
	@Id int,
	@NIT int,
	@Name nvarchar(100),
	@Email nvarchar(100),
	@ServicesId int
AS

SET NOCOUNT ON

IF EXISTS(SELECT [Id] FROM [dbo].[Supplier] WHERE [Id] = @Id)
BEGIN
	UPDATE [dbo].[Supplier] SET
		[NIT] = @NIT,
		[Name] = @Name,
		[Email] = @Email,
		[ServicesId] = @ServicesId
	WHERE
		[Id] = @Id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Supplier] (
		[Id],
		[NIT],
		[Name],
		[Email],
		[ServicesId]
	) VALUES (
		@Id,
		@NIT,
		@Name,
		@Email,
		@ServicesId
	)
END

--endregion

GO

--region [dbo].[sp_DeleteSupplier]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteSupplier]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteSupplier]
	@Id int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Supplier]
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_DeleteSuppliersByServicesId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteSuppliersByServicesId]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteSuppliersByServicesId]
	@ServicesId int
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Supplier]
WHERE
	[ServicesId] = @ServicesId

GO

--endregion

GO

--region [dbo].[sp_DeleteSuppliersDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_DeleteSuppliersDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_DeleteSuppliersDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Supplier]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectSupplier]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectSupplier]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectSupplier]
	@Id int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[NIT],
	[Name],
	[Email],
	[ServicesId]
FROM
	[dbo].[Supplier]
WHERE
	[Id] = @Id

--endregion

GO

--region [dbo].[sp_SelectSuppliersByServicesId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectSuppliersByServicesId]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectSuppliersByServicesId]
	@ServicesId int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[NIT],
	[Name],
	[Email],
	[ServicesId]
FROM
	[dbo].[Supplier]
WHERE
	[ServicesId] = @ServicesId

--endregion

GO

--region [dbo].[sp_SelectSuppliersDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectSuppliersDynamic]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectSuppliersDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[Id],
	[NIT],
	[Name],
	[Email],
	[ServicesId]
FROM
	[dbo].[Supplier]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[sp_SelectSuppliersAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectSuppliersAll]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectSuppliersAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[NIT],
	[Name],
	[Email],
	[ServicesId]
FROM
	[dbo].[Supplier]

--endregion

GO

--region [dbo].[sp_SelectSuppliersPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   GUERRERO using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[sp_SelectSuppliersPaged]
-- Date Generated: jueves, 9 de marzo de 2023
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[sp_SelectSuppliersPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[Id],
	[NIT],
	[Name],
	[Email],
	[ServicesId]
FROM
	[dbo].[Supplier]

--endregion

GO

